### ISSUE TITLE
stop at "r = algorithms.eaSimple()"

### ISSUE THREAD

**Issue by lemo2012** [aqibsaeed/Genetic-Algorithm-RNN#1]
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    r = algorithms.eaSimple(population, toolbox, cxpb = 0.4, mutpb = 0.1, ngen = num_generations, verbose = False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/deap/algorithms.py", line 152, in eaSimple
    ind.fitness.values = fit
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/deap/base.py", line 185, in setValues
    self.wvalues = tuple(map(mul, values, self.weights))
TypeError: Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMax'>. Currently assigning value(s) 0.076375786869707959 of <type 'numpy.float64'> to a fitness with weights (-1.0,).

**Comment by aqibsaeed** [comment]
The objective function must return a tuple of a single element. You can create a single element tuple using a trailing comma.

`def train_evaluate:
......
return rmse, # notice "," at the end
`
